Question-1

In [10]:
import numpy as np
import pandas as pd

arr1 = np.arange(1, 51)
arr2 = np.random.randint(10, 101, (6, 6))
arr3 = np.ones((3, 3, 3), dtype=int)
print(arr3)
print(arr2)
print(arr1)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
[[27 18 63 66 41 25]
 [26 59 52 61 99 19]
 [76 71 93 54 84 94]
 [25 29 97 88 20 18]
 [78 59 79 81 35 43]
 [57 43 16 51 62 19]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [ ]:
Q-2.

In [13]:
eye_mat = np.eye(5)
identity_mat = np.identity(5)
print(eye_mat)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
Q-3.

In [14]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2
power = arr1 ** arr2
print(mul)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
Q-4.

In [15]:
arr = np.arange(1, 37)

a = arr.reshape(6,6)
b = arr.reshape(3,3,4)
print(a)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [ ]:
Q-5.

In [16]:
rand_ints = np.random.randint(1, 101, 10)
rand_floats = np.random.rand(4,4)
print(rand_ints)

[75 54  5 13  5  1 87 62 50 76]


In [ ]:
Q-6.

In [17]:
arr = np.random.randint(0, 51, 15)
asc = np.sort(arr)
desc = np.sort(arr)[::-1]
print(asc)

[ 0  1  2  3  4  6 16 17 34 34 39 39 45 45 47]


In [ ]:
Q-7.

In [18]:
arr = np.array([1,2,2,3,4,4,4,5])
unique_vals, counts = np.unique(arr, return_counts=True)
print(counts)

[1 2 1 3 1]


In [ ]:
Q-8.

In [21]:
arr = np.random.randint(50, 101, 20)
mean = np.mean(arr)
median = np.median(arr)
var = np.var(arr)
std = np.std(arr)
mn = np.min(arr)
mx = np.max(arr)
print(mn)
print(std)

52
16.31341472531119


In [ ]:
Q-9.

In [24]:
mat = np.array([[1,2,3],[4,5,6],[7,8,10]])
det = np.linalg.det(mat)
transpose = mat.T
inverse = np.linalg.inv(mat)
print(transpose)
print(inverse)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


Q-10.

In [37]:
data = {
    "Name": ["Umang","jay","shyam","Trush","jimesh","Karan","Meera","Ravi","Simran","darshan"],
    "Age": [20,21,22,23,21,22,24,23,20,22],
    "Department": ["CSE","ECE","CSE","IT","ECE","CSE","ME","IT","CSE","ME"],
    "CGPA": [9.1,7.8,8.5,8.9,7.2,9.3,8.0,7.5,9.0,8.4]
}
df = pd.DataFrame(data)

#Q-11.
#first5 = df.head()
#last3 = df.tail(3)
#summary = df.describe()
#sorted_df = df.sort_values(by=["Age","CGPA"])
#print(sorted_df)

#Q-12.
'''dept_col = df["Department"]
cgpa_above = df[df["CGPA"] > 8.5]
name_cgpa = df.loc[:4, ["Name","CGPA"]]
print(name_cgpa)'''

#Q-13.
'''df.loc[2,"CGPA"] = np.nan  
dropna_df = df.dropna()
fillna_df = df.fillna(df["CGPA"].mean())
print(fillna_df)'''

#Q-14.
#cse_above8 = df[(df["Department"]=="CSE") & (df["CGPA"]>8)]
#print(cse_above8)

#Q-15.
#avg_cgpa = df.groupby("Department")["CGPA"].mean()
#print(avg_cgpa)

#Q-16.
#df["Scholarship"] = np.where(df["CGPA"]>8.5, "Yes", "No")
#print(df)

#Q-17.
'''intern_data = {
    "Name":["Aditi","Rahul","Neha","Arjun","Priya"],
    "Internship":["Yes","No","Yes","No","Yes"]
}
df2 = pd.DataFrame(intern_data)
merged = pd.merge(df, df2, on="Name", how="left")
print(merged)'''

      Name  Age Department  CGPA Internship
0    Umang   20        CSE   9.1        NaN
1      jay   21        ECE   7.8        NaN
2    shyam   22        CSE   8.5        NaN
3    Trush   23         IT   8.9        NaN
4   jimesh   21        ECE   7.2        NaN
5    Karan   22        CSE   9.3        NaN
6    Meera   24         ME   8.0        NaN
7     Ravi   23         IT   7.5        NaN
8   Simran   20        CSE   9.0        NaN
9  darshan   22         ME   8.4        NaN


In [ ]:
Q-18.

In [42]:
data = {
    "RollNo":[101,102,103,104,105,106,107,108,109,110,
              111,112,113,114,115,116,117,118,119,120],
    "Name":["Aditi","Rahul","Neha","Arjun","Priya","Karan","Meera","Ravi","Simran","Ishaan",
            "Ankit","Pooja","Nikhil","Sneha","Vikas","Aman","Riya","Saurabh","Deepa","Manish"],
    "Marks_ML":[78,65,89,56,92,75,88,61,70,95,
                81,72,68,85,60,91,77,83,66,74],
    "Marks_DS":[85,70,82,60,88,69,79,72,67,90,
                86,73,64,80,59,87,71,84,63,76],
    "Marks_AI":[92,68,84,65,90,77,81,74,69,93,
                89,70,66,82,62,88,75,85,64,78],
    "Department":["CSE","ECE","IT","CSE","ECE","IT","CSE","ME","CSE","ME",
                  "ECE","CSE","IT","ECE","ME","CSE","IT","CSE","ECE","ME"]
}
df = pd.DataFrame(data)
df.to_csv("students.csv", index=False)

df_csv = pd.read_csv("students.csv")

df_csv["Total"] = df_csv[["Marks_ML","Marks_DS","Marks_AI"]].sum(axis=1)
df_csv["Percentage"] = df_csv["Total"] / 300 * 100

top2 = df_csv.groupby("Department").apply(lambda x: x.nlargest(2, "Total")).reset_index(drop=True)

avg_marks = df_csv[["Marks_ML","Marks_DS","Marks_AI"]].mean()
print(avg_marks)

Marks_ML    76.30
Marks_DS    75.25
Marks_AI    77.60
dtype: float64


C:\Users\hp\AppData\Local\Temp\ipykernel_12672\700949743.py:23: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top2 = df_csv.groupby("Department").apply(lambda x: x.nlargest(2, "Total")).reset_index(drop=True)
